version: '2'
services:
  terito-app:
    image: terito
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://terito-postgresql:5432/terito
      - JHIPSTER_CACHE_REDIS_SERVER=redis://terito-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://terito-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://terito-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://terito-elasticsearch:9200
    ports:
      - 8080:8080
  terito-postgresql:
    extends:
      file: postgresql.yml
      service: terito-postgresql
  terito-redis:
    extends:
      file: redis.yml
      service: terito-redis
  terito-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: terito-elasticsearch
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
